name: lorien_chat_list
description: >
  Flutter plugin for creating chat list page which will automatically 
  scroll or maintain current scroll position.

version: 0.0.3
repository: https://github.com/lorien-dev/chat_list

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
